### ISSUE TITLE
GraphQl Caching

### ISSUE THREAD

**Issue by MaxSouza** [discorgento/module-product-last-order#10]
Is it possible to change the GraphQL query method from POST to GET? 

With the GET method, we can implement a cache for this query.

Something like that:

![image](https://github.com/discorgento/module-product-last-order/assets/5350377/07cb77d1-ea5a-4292-beae-75865cbe6488)

We're making requests to customers and order data, which could be offensive to page load.

**Comment by jonatanaxe** [comment]
I think it's possible yes, I don't have much experience with graphql yet, but I'll look into it.

If you want to do a PR of this feel free too

**Comment by MaxSouza** [comment]
So I'm gonna working on this

**Comment by jonatanaxe** [comment]
Thanks for the PR 🚀 Close: https://github.com/discorgento/module-product-last-order/pull/11
